# Configuración de prueba para Coolify
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.coolify
    ports:
      - "82:82"
    environment:
      - NODE_ENV=production
    restart: unless-stopped