version: '3.8'

services:
  # Servicio de desarrollo
  rrhh-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev

  # Servicio de producción
  rrhh-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:81"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod

networks:
  default:
    driver: bridge